[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablecoin = "Co32qABaBxtzVNmSmQ82v5MXzcCvRvUb23FmfW6Ko7JR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
